spring:
  application:
    name: name-service
  cloud:
    config:
        url: http://localhost:6061
    client:
      enabled: true    
      
eureka:
  client:
    service-url:
       defaultZone: http://localhost:9091/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    
server:
  port: 0 
  
config:
  names:
    Abdul Hafeez
    Abdul Sattart
    Muhammed Haris
    Muhammed Umair
    Muahmmed Taha
    Muhammed Umer
    Muhammed Talha
    