spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:vehicledb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    platform: h2

config:
  ping-delay: 60000        
  